# Pydantic models for FinEd Personal Lens
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any


class PersonalLensAnswer(BaseModel):
    """An individual answer to a questionnaire step"""
    question: Optional[str] = Field(None, description="Question text")
    question_id: Optional[str] = Field(None, description="Optional question ID or index")
    option_id: Optional[str] = Field(None, description="Optional option ID or index")
    label: Optional[str] = Field(None, description="Readable label of the selected option")
    answer: Optional[str] = Field(None, description="Selected answer text")


class PersonalLensRequest(BaseModel):
    """Request payload from client to generate or fetch a personal lens"""
    article_id: str = Field(..., description="Article UUID or slug")
    answers: List[PersonalLensAnswer] = Field(..., min_length=1, max_length=10, description="List of user questionnaire answers")


class PersonalLensResult(BaseModel):
    """The structured lens takeaways generated by AI or retrieved from cache"""
    why_it_matters: str = Field(..., alias="whyItMatters", description="Why this article is relevant to the reader's personal context")
    personal_summary: str = Field(..., alias="personalSummary", description="Plain English customized summary tailored to reader level")
    focus_sections: List[str] = Field(..., alias="focusSections", description="Key section titles the reader should prioritize")
    takeaway: str = Field(..., description="One single core concept takeaway")
    what_to_do: Optional[str] = Field(None, alias="whatToDo", description="Practical next educational step or habit suggestion")

    class Config:
        populate_by_name = True


class PersonalLensResponse(BaseModel):
    """Full API response for personal lens endpoint"""
    article_id: str = Field(..., alias="articleId")
    profile_key: str = Field(..., alias="profileKey")
    cached: bool = Field(False, description="Whether this response was served from database cache")
    lens: PersonalLensResult

    class Config:
        populate_by_name = True


class ArticleQuestion(BaseModel):
    id: Optional[str] = None
    article_id: Optional[str] = None
    question: str
    display_order: int = 0
    options: List[Any] = []

